eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #设置与eureka server 交互地址，查询服务和注册服务都依赖这个地址。
    register-with-eureka: false #是否将自己注册到 eureka server，默认为true
#应用名称
spring:
  application:
    name: eurekaServer
#项目端口号
server:
  port: 8761
